"""GISS ModelE convection scheme infrastructure.

Holds the model-specific parameter and diagnostic containers consumed by the
GISS convection term (:class:`jcm.physics.convection.giss_mstcnv.GissConvection`),
mirroring how ``speedy/`` and ``icon/`` hold their own infrastructure:

* :mod:`jcm.physics.modele.params` -- ``GissConvectionParameters``.
* :mod:`jcm.physics.modele.physics_data` -- ``GissConvectionData``.

The ModelE oracle **reading and conversion** tooling (NetCDF reader, oracle ->
``PhysicsState`` adapter) deliberately lives in a *separate* repository, not in
JCM. This repo only carries committed fixture arrays (``jcm/data/test/modele/``)
generated by that tooling, used by the scheme's unit tests -- the same pattern
the SPEEDY convection tests use for their ``.npy`` oracle arrays.
"""

from jcm.physics.modele import params  # noqa: F401
from jcm.physics.modele import physics_data  # noqa: F401
